services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./server:/app
    ports:
      - "8080:8080"
    depends_on:
      - "database"
    networks:
      - "food_app"

  database:
    image: "arm64v8/mysql:8.0.41"
    container_name: "db-mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "food_app"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "password"
    networks:
      - "food_app"

  migrate:
    image: migrate/migrate
    volumes:
      - ./server/repository/migrations:/migrations
    entrypoint: [
      "migrate",
      "-path=/migrations",
      "-database=mysql://root:password@tcp(database:3306)/food_app"
    ]
    depends_on:
      - database
    networks:
      - "food_app"


networks:
  food_app:
    driver: "bridge"